server:
  port: 4000

management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: "always"

spring:
  application:
    name: fpl-service

idam:
  s2s-auth:
    microservice: fpl_case_service

---

spring:
  profiles: integration-test

management:
  endpoints:
    enabled-by-default: false

idam:
  api:
    url: http://fake-idam-api
  s2s-auth:
    url: http://fake-service-auth-provider-api
    totp_secret: AABBCCDDEEFFGGHH

core_case_data:
  api:
    url: http://fake-ccd-data-store-api

document_management:
  url: http://fake-document-management-store-api

notify:
  api_key: testApiKey

ccd:
  ui:
    base:
      url: http://fake-url

fpl:
  local_authority_email_to_code:
    mapping: 'example.gov.uk=>example'
  local_authority_code_to_name:
    mapping: 'example=>Example Local Authority'
  local_authority_code_to_hmcts_court:
    mapping: 'example=>Family Court:admin@family-court.com'
  local_authority_code_to_cafcass:
    mapping: 'example=>cafcass:cafcass@cafcass.com'
  local_authority_user:
    mapping: 'example=>1,2,3'

---

spring:
  profiles: local

idam:
  api:
    url: http://localhost:5000
  s2s-auth:
    url: http://localhost:4502
    totp_secret: AABBCCDDEEFFGGHH

core_case_data:
  api:
    url: http://localhost:4452

document_management:
  url: http://localhost:4506

notify:
  api_key: fake-key

ccd:
  ui:
    base:
      url: http://localhost:3451

appinsights:
  instrumentationkey: fake-key

fpl:
  local_authority_email_to_code:
    mapping: 'fpla.local=>FPLA;swansea.gov.uk=>SA;hillingdon.gov.uk=>HN'
  local_authority_code_to_name:
    mapping: 'SA=>Swansea City Council;HN=>London Borough Hillingdon;PCC=>Portsmouth City Council;STF=>Staffordshire County Council;SCC=>Southampton City Council'
  local_authority_code_to_hmcts_court:
    mapping: 'SA=>Swansea Family Court:FamilyPublicLaw+sa@gmail.com;HN=>Portsmouth Combined Court:FamilyPublicLaw+hn@gmail.com'
  local_authority_code_to_cafcass:
    mapping: 'SA=>Cafcass Cymru:FamilyPublicLaw+cafcassWales@gmail.com;HN=>Cafcass:FamilyPublicLaw+cafcassEngland@gmail.com'
  local_authority_user:
    mapping: 'FPLA=>0;SA=>acfe91d3-745f-4e60-8272-2cada36152a5,bbea68ea-081b-467c-8574-4c246cdc06d7,b10076d3-e191-4793-94fb-d5c5bacc470b;HN=>b91e9823-09fa-448d-a583-46796100f07e,3fad4b19-9622-4e93-905a-c3448e537ef4'
